set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'dracula/tmux'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'omerxx/tmux-sessionx'

set -g mouse on

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

set -g @sessionx-fzf-builtin-tmux 'on'
set -g @sessionx-bind '0'
set -g @sessionx-window-mode 'on'
set -g @sessionx-tree-mode 'on'

run '~/.tmux/plugins/tpm/tpm'

